resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/Davis1557/ConcourseTest.git
      branch: master
  - name: git-repo2
    type: git
    source:
      uri: https://github.com/Davis1557/ConcourseTest2.git
      branch: master
      username: davis1557
      password: Tobe0912

jobs:
  - name: repo_to_repo2
    max_in_flight: 1
    plan:
      - in_parallel:
        - get: git-repo
          trigger: true
        - get: git-repo2
      - task: maven-package
        config:
          platform: linux
          image: test-image
          image_resource:
            type: docker-image
            source:
              repository: vm.docker.internal:5000/maven
              tag: by-davis
              username: docker
              password: docker
              ca_certs:
                - domain: vm.docker.internal:5000
                  cert: ((docker-registry-ca))
          inputs:
            - name: git-repo
            - name: git-repo2
          outputs:
            - name: git-repo2
          run:
            path: /bin/bash
            args:
              - -c
              - |
                export DT=$(date +"%Y%m%d%H%M%S")
                cd git-repo
                mvn clean package
                echo "Move Jar To Release Dir"
                mkdir -p ../git-repo2/${DT}
                cp target/*.jar ../git-repo2/${DT}/
                cd ../git-repo2
                git config --global user.name "Davis"
                git config --global user.email "davis@aitc.com.tw"
                git add **/*
                git commit -m "Upload by Davis"
      - put: git-repo2
        params:
          repository: git-repo2