resource_types:
  - name: registry-image-davis
    type: docker-image
    source:
      repository: vm.docker.internal:5000/concourse/registry-image-resource
      privileged: true
      tag: by-davis
      username: docker
      password: docker
      ca_certs:
        - domain: vm.docker.internal:5000
          cert: ((docker-registry-ca))

resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/Davis1557/ConcourseTest.git
      branch: master
  - name: git-release
    type: github-release
    source:
      owner: Davis1557
      repository: ConcourseTest
      access_token: 6251710980b1287d1e77d66ff6b9058fff5f6a08
  - name: test-image
    type: registry-image-davis
    source:
      repository: vm.docker.internal:5000/maven
      tag: by-davis
      username: docker
      password: docker

jobs:
  - name: repo_to_release
    max_in_flight: 1
    plan:
      - get: git-repo
        trigger: true
      - get: test-image
      - task: maven-package
        image: test-image
        config:
          platform: linux
          inputs:
            - name: git-repo
          outputs:
            - name: release
          run:
            path: /bin/bash
            args:
              - -c
              - |
                export DT=$(date +"%Y%m%d%H%M%S")
                cd git-repo
                mvn clean package
                echo "Move Jar To Release Dir"
                mkdir -p release/${DT}
                cp target/*.jar ../release
                echo "SBE" >> ../release/name
                echo "${DT}" >> ../release/tag
      - put: git-release
        params:
          name: release/name
          tag: release/tag
          globs:
            - release/*.jar