resource_types:
  - name: registry-image-davis
    type: docker-image
    source:
      repository: vm.docker.internal:5000/concourse/registry-image-resource
      tag: by-davis
      username: docker
      password: docker
      ca_certs:
        - domain: vm.docker.internal:5000
          cert: ((docker-registry-ca))

resources:
  - name: git-repo
    type: git
    icon: github
    source:
      uri: https://github.com/Davis1557/ConcourseTest.git
      branch: master
  - name: git-release
    type: github-release
    icon: github
    source:
      owner: Davis1557
      repository: ConcourseTest
      access_token: a38257ff24282bed65142b9aa880e1f2c731fb5e
  - name: maven-image
    type: registry-image-davis
    icon: oci
    source:
      repository: vm.docker.internal:5000/maven
      tag: by-davis
      username: docker
      password: docker

jobs:
  - name: repo_to_release
    plan:
      - in_parallel:
        - get: git-repo
          trigger: true
        - get: maven-image
      - task: maven-package
        image: maven-image
        config:
          platform: linux
          inputs:
            - name: git-repo
          outputs:
            - name: release
          run:
            path: /bin/bash
            args:
              - -c
              - |
                export DT=$(date +"%Y%m%d%H%M%S")
                cd git-repo
                mvn clean package
                echo "Move Jar To Release Dir"
                mkdir -p release/${DT}
                cp target/*.jar ../release
                echo "SBE" >> ../release/name
                echo "${DT}" >> ../release/tag
      - put: git-release
        params:
          name: release/name
          tag: release/tag
          globs:
            - release/*.jar