resources:
  - name: simple-res
    type: registry-image
    source:
      repository: busybox

jobs:
  - name: job
    plan:
      - get: simple-res
      - task: task-1
        image: simple-res
        config:
          platform: linux
          run:
            path: echo
            args: ["task-1"]
        on_success:
          task: task-1-success
          image: simple-res
          config:
            platform: linux
            run:
              path: echo
              args: ["task-1-success"]
      - task: task-2
        image: simple-res
        config:
          platform: linux
          run:
            path: echo
            args: ["task-2"]