resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/Davis1557/ConcourseTest.git
      branch: master
  - name: git-repo2
    type: git
    source:
      uri: https://github.com/Davis1557/ConcourseTest2.git
      branch: master
      username: davis1557
      password: Tobe0912

jobs:
  - name: repo_to_repo2
    max_in_flight: 1
    plan:
      - get: git-repo
        trigger: true
      - get: git-repo2
      - task: maven-package
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: vm.docker.internal:5000/maven
              tag: 3.6.3-slim
              insecure_registries:
                - vm.docker.internal:5000
          inputs:
            - name: git-repo
            - name: git-repo2
          outputs:
            - name: git-repo2
          run:
            path: /bin/bash
            args:
              - -c
              - |
                export DT=$(date +"%Y%m%d%H%M%S")
                cd git-repo
                mvn clean package -s settings.xml
                echo "Move Jar To Release Dir"
                mkdir -p ../git-repo2/${DT}
                cp target/*.jar ../git-repo2/${DT}/
      - task: git-commit
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: vm.docker.internal:5000/concourse/git-resource
              insecure_registries:
                - vm.docker.internal:5000
          inputs:
            - name: git-repo2
          outputs:
            - name: git-repo2
          run:
            path: /bin/bash
            args:
              - -c
              - |
                cd git-repo2
                git add **/*
                git commit -m "by Davis"
      - put: git-repo2
        params:
          repository: git-repo2