resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/Davis1557/ConcourseTest.git
      branch: master

  - name: git-release
    type: git
    source:
      uri: https://github.com/Davis1557/ConcourseTest.git
      branch: release


jobs:
  - name: job
    plan:
      - get: git-repo
        trigger: true
      - task: maven-package
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: maven
              tag: 3.6.3-slim
          inputs:
            - name: git-repo
          caches:
            - path: /root/.m2
          params:
            ECHO_TEST: hello-world
          run:
            path: /bin/bash
            args:
              - -c
              - |
                echo ${ECHO_TEST}
                cd git-repo
                mvn clean package